const Images = {
  siginbackgroundimage: require('../../assets/images/app_background21.jpg'),
  openhouse: require('../../assets/images/open_house.png'),
  back1: require('../../assets/images/back1.png'),
  loadinggif: require('../../assets/images/loading.gif'),
  property: require('../../assets/images/property_hp.png'),
  event: require('../../assets/images/events_hp.png'),
  lead: require('../../assets/images/lead_hp.png'),
  question: require('../../assets/images/questions_hp.png'),
  mls: require('../../assets/images/mls_hp.png'),
  mortgage: require('../../assets/images/mortgage_hp.png'),
  profile: require('../../assets/images/profile_hp.png'),
  support: require('../../assets/images/support_hp.png'),
  switch_layout: require('../../assets/images/switch_layout.png'),
  logout: require('../../assets/images/logou_hp.png'),
  backicon: require('../../assets/images/back2.png'),
  start_openhouse: require('../../assets/images/start_openhouse.png'),
  share_property: require('../../assets/images/share_property.png'),
  add_photo: require('../../assets/images/add_photo.png'),
  manage_attendees: require('../../assets/images/manage_attendees.png'),
  cancel: require('../../assets/images/cancel.png'),
  lock: require('../../assets/images/lock.png'),
  createicon: require('../../assets/images/add_small.png'),
  avataricon: require('../../assets/images/avatar.png'),
  partnericon: require('../../assets/images/partner.png'),
  checkmarkicon: require('../../assets/images/checkmark.png'),
  itemshowicon: require('../../assets/images/itme_showbtn.png'),
  ic_upload: require('../../assets/images/ic_upload.png'),
  export: require('../../assets/images/export.png'),
  defaultmortgage: require('../../assets/images/house.jpg'),
  add_data: require('../../assets/images/add_data.png'),
  more_menue: require('../../assets/images/more_menu.png'),
  delete_icon: require('../../assets/images/delete_icon.png'),
  main_menu_technical_support: require('../../assets/images/main_menu_technical_support.png'),
};

export default Images;
